# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Neighbourhoods' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'TZImagePickerController'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'JPush'
# pod 'JMessage'

  # Pods for Neighbourhoods
  # MOB
  pod 'SMSSDK'
  pod 'MOBFoundation'

  # Pods for IM
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'YHPopupView'
  pod 'YHPhotoKit'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'FMDB', '~> 2.6.2'
  pod 'JMessage', '~> 3.3.0’
  pod 'RxSwift', '~> 3.6.1'
  pod 'RxCocoa', '~> 3.6.1'


end
