# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Neighbourhoods' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'TZImagePickerController'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'JPush'
# pod 'JMessage'

# Pods for ShareSDK

# 主模块(必须)
  pod 'ShareSDK3'

# 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
  pod 'ShareSDK3/ShareSDKPlatforms/QQ'
  pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
  pod 'ShareSDK3/ShareSDKPlatforms/WeChat'


  # Pods for Neighbourhoods
  # MOB
  pod 'SMSSDK'
  pod 'MOBFoundation'

  # Pods for IM
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'YHPopupView'
  pod 'YHPhotoKit'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'FMDB', '~> 2.6.2'
  pod 'JMessage', '~> 3.3.0’
  pod 'RxSwift', '~> 3.6.1'
  pod 'RxCocoa', '~> 3.6.1'


end
