# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Neighbourhoods' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'TZImagePickerController'
  pod 'MJRefresh'
  pod 'MJExtension'

  # Pods for Neighbourhoods

end
